name: package_teste
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0-38.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  hive: ^2.2.3
  shared_preferences: ^2.2.1
  hive_flutter: ^1.1.0
  path_provider: ^2.0.15
  get: ^4.6.6
  flutter_form_builder: ^9.1.0
  get_it: ^7.6.4
  dartz: ^0.10.1
  dio: ^5.3.3
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  build_runner: ^2.4.6
  provider: ^6.0.5
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/data.json
